src/Entity/Companies.php
<?php

namespace App\Entity;

use App\Repository\CompaniesRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CompaniesRepository::class)
 */
class Companies
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $num_employees;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getNumEmployees(): ?int
    {
        return $this->num_employees;
    }

    public function setNumEmployees(?int $num_employees): self
    {
        $this->num_employees = $num_employees;

        return $this;
    }
}

src/Form/CompaniesType.php
<?php

namespace App\Form;

use App\Entity\Companies;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CompaniesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('city')
            ->add('num_employees')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Companies::class,
        ]);
    }
}

src/Controller/CompaniesController.php
<?php

namespace App\Controller;

use App\Entity\Companies;
use App\Form\CompaniesType;
use App\Repository\CompaniesRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/companies")
 */
class CompaniesController extends AbstractController
{
    /**
     * @Route("/", name="companies_index", methods={"GET"})
     */
    public function index(CompaniesRepository $companiesRepository): Response
    {
        return $this->render('companies/index.html.twig', [
            'companies' => $companiesRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="companies_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $company = new Companies();
        $form = $this->createForm(CompaniesType::class, $company);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($company);
            $entityManager->flush();

            return $this->redirectToRoute('companies_index');
        }

        return $this->render('companies/new.html.twig', [
            'company' => $company,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="companies_show", methods={"GET"})
     */
    public function show(Companies $company): Response
    {
        return $this->render('companies/show.html.twig', [
            'company' => $company,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="companies_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Companies $company): Response
    {
        $form = $this->createForm(CompaniesType::class, $company);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('companies_index');
        }

        return $this->render('companies/edit.html.twig', [
            'company' => $company,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="companies_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Companies $company): Response
    {
        if ($this->isCsrfTokenValid('delete'.$company->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($company);
            $entityManager->flush();
        }

        return $this->redirectToRoute('companies_index');
    }
}

templates/companies/_delete_form.html.twig
<form method="post" action="{{ path('companies_delete', {'id': company.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ company.id) }}">
    <button class="btn">Delete</button>
</form>

templates/companies/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/companies/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Companies{% endblock %}

{% block body %}
    <h1>Edit Companies</h1>

    {{ include('companies/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('companies_index') }}">back to list</a>

    {{ include('companies/_delete_form.html.twig') }}
{% endblock %}

templates/companies/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Companies index{% endblock %}

{% block body %}
    <h1>Companies index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>City</th>
                <th>Num_employees</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for company in companies %}
            <tr>
                <td>{{ company.id }}</td>
                <td>{{ company.name }}</td>
                <td>{{ company.city }}</td>
                <td>{{ company.numEmployees }}</td>
                <td>
                    <a href="{{ path('companies_show', {'id': company.id}) }}">show</a>
                    <a href="{{ path('companies_edit', {'id': company.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('companies_new') }}">Create new</a>
{% endblock %}

templates/companies/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Companies{% endblock %}

{% block body %}
    <h1>Create new Companies</h1>

    {{ include('companies/_form.html.twig') }}

    <a href="{{ path('companies_index') }}">back to list</a>
{% endblock %}

templates/companies/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Companies{% endblock %}

{% block body %}
    <h1>Companies</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ company.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ company.name }}</td>
            </tr>
            <tr>
                <th>City</th>
                <td>{{ company.city }}</td>
            </tr>
            <tr>
                <th>Num_employees</th>
                <td>{{ company.numEmployees }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('companies_index') }}">back to list</a>

    <a href="{{ path('companies_edit', {'id': company.id}) }}">edit</a>

    {{ include('companies/_delete_form.html.twig') }}
{% endblock %}